# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedRegion',
            fields=[
                ('loci_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chr', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('width', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=30)),
                ('details', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MelanomaExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('expression', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SnpsByLoci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=200)),
                ('pubmed', models.IntegerField()),
                ('pvalue', models.CharField(max_length=10)),
                ('captured_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snps_details', to='capseq.CapturedRegion')),
            ],
        ),
        migrations.CreateModel(
            name='TissueExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('expression', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='traitsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('efo_term', models.CharField(max_length=200)),
                ('efo_link', models.CharField(max_length=200)),
                ('parent_term', models.CharField(max_length=200)),
                ('parent_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('exons', jsonfield.fields.JSONField()),
            ],
        ),
    ]
