# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('width', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MelanomaExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('expression', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TissueExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('expression', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('exons', jsonfield.fields.JSONField()),
            ],
        ),
    ]
