# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_id', models.CharField(max_length=30)),
                ('chrom', models.CharField(max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MelanomaExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('gene_name', models.CharField(max_length=30)),
                ('expression', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TissueExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('expression', models.TextField()),
            ],
        ),
    ]
