# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedregion',
            name='track',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
