# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 10:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melanomaexpression',
            name='expression',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='tissueexpression',
            name='expression',
            field=jsonfield.fields.JSONField(),
        ),
    ]
