# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snpsbyloci',
            name='pubmed',
            field=models.IntegerField(null=True),
        ),
    ]
