# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0002_auto_20160229_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=30)),
                ('exons', jsonfield.fields.JSONField()),
            ],
        ),
    ]
