# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0002_capturedregion_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedregion',
            name='details',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
