# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0002_auto_20160513_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snpsbyloci',
            name='disease',
        ),
        migrations.AddField(
            model_name='snpsbyloci',
            name='disease_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traitsdetails',
            name='disease_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
