# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0003_auto_20160515_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='regionToTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loci_id', models.IntegerField()),
                ('transcript_id', models.CharField(max_length=30)),
            ],
        ),
    ]
