# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capseq', '0004_regiontotx'),
    ]

    operations = [
        migrations.CreateModel(
            name='snpSpecificLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp_id', models.CharField(max_length=30)),
                ('chr', models.CharField(max_length=5)),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
            ],
        ),
    ]
